import { db } from "./index";
import { products, admins, storeSettings, reviews } from "./schema";
import bcrypt from "bcryptjs";
import { count } from "drizzle-orm";

export async function seedDatabase() {
  try {
    // Check if products already exist
    const [{ value: productCount }] = await db.select({ value: count() }).from(products);

    // Seed Admin if not exists
    const [{ value: adminCount }] = await db.select({ value: count() }).from(admins);
    if (Number(adminCount) === 0) {
      const seedEmail = process.env.SEED_ADMIN_EMAIL || "admin@daudfabrics.pk";
      const seedPassword = process.env.SEED_ADMIN_PASSWORD || "admin123";
      const passwordHash = await bcrypt.hash(seedPassword, 10);
      await db.insert(admins).values({
        email: seedEmail,
        passwordHash,
        name: "Daud Ahmed (Admin)",
        role: "admin",
      });
      console.log(`Seed: Admin account created (${seedEmail})`);
    }

    // Seed Store Settings if not exists
    const [{ value: settingsCount }] = await db.select({ value: count() }).from(storeSettings);
    if (Number(settingsCount) === 0) {
      await db.insert(storeSettings).values([
        { key: "easypaisa_title", value: "Daud Fabrics / Daud Ahmed" },
        { key: "easypaisa_number", value: "0327-5363509" },
        { key: "easypaisa_instructions", value: "Send payment to the EasyPaisa number above, then upload a screenshot of the transaction receipt below." },
        { key: "meezan_bank_title", value: "Daud Fabrics Pvt Ltd" },
        { key: "meezan_bank_account", value: "0289-0105829101" },
        { key: "meezan_bank_iban", value: "PK65MEZN0002890105829101" },
        { key: "meezan_bank_branch", value: "Gulberg III Main Branch, Lahore" },
        { key: "meezan_bank_instructions", value: "Transfer the order total to our Meezan Bank account via Raast or Online Banking. Upload your transfer receipt/screenshot proof below." },
        { key: "store_phone", value: "+92 327 5363509" },
        { key: "store_whatsapp", value: "923275363509" },
        { key: "store_email", value: "sales@daudfabrics.pk" },
        { key: "store_address", value: "Shop # 14-18, Daud Fabrics Arcade, Main Liberty Market, Gulberg III, Lahore" },
        { key: "free_shipping_threshold", value: "3000" },
        { key: "standard_shipping_fee", value: "250" },
        { key: "announcement_messages", value: JSON.stringify([
          "✨ FREE Shipping Across Pakistan on Orders Above Rs 3,000",
          "🇵🇰 Premium Authentic Pakistani Fabrics — 100% Original Guarantee",
          "🔥 New Festive Luxury Lawn, Shawls & Boski Collection Live",
          "⚡ Cash on Delivery (COD) & EasyPaisa / Meezan Bank Available"
        ])},
      ]);
      console.log("Seed: Store settings initialized");
    }

    // Seed Reviews if not exists
    const [{ value: reviewCount }] = await db.select({ value: count() }).from(reviews);
    if (Number(reviewCount) === 0) {
      await db.insert(reviews).values([
        {
          customerName: "Mian Hamza Tariq",
          city: "Lahore (Gulberg)",
          rating: 5,
          comment: "Sublime quality! The Kashmiri Wool Shawl has that crisp, royal fall. Received parcel in Gulberg within 24 hours. Truly authentic Pakistani craftsmanship.",
          productName: "Kashmiri Wool Embroidered Shawl — Signature Black",
          verified: true,
        },
        {
          customerName: "Dr. Ayesha Siddiqui",
          city: "Karachi (Clifton)",
          rating: 5,
          comment: "The Embroidered Luxury Lawn 3-piece is breathtaking. The colors did not bleed, fabric is buttery soft for Karachi summers, and the chiffon dupatta is featherlight.",
          productName: "Luxury Embroidered Swiss Lawn 3-Piece — Rose Bloom",
          verified: true,
        },
        {
          customerName: "Chaudhry Usman",
          city: "Islamabad (F-7)",
          rating: 5,
          comment: "I have ordered Boski and Shawls twice now from Daud Fabrics. Best unstitched fabric in Pakistan at very reasonable pricing.",
          productName: "Classic Superfine Boski Silk Suit — 7.5m Fall Finish",
          verified: true,
        },
        {
          customerName: "Zainab Farooq",
          city: "Faisalabad",
          rating: 5,
          comment: "Living in the textile hub Faisalabad, I am very picky with fabrics. Daud Fabrics exceeded my expectations. Outstanding thread count and fast delivery!",
          productName: "Pure Silk Jacquard Festive 3-Piece — Champagne Gold",
          verified: true,
        },
        {
          customerName: "Taimoor Ali Khan",
          city: "Peshawar",
          rating: 5,
          comment: "EasyPaisa payment verification was super quick. Got tracking number from Trax/TCS on WhatsApp. Suit looks majestic for Friday prayers.",
          productName: "Heritage Pashmina Wool Shawl — Walnut Brown",
          verified: true,
        },
      ]);
      console.log("Seed: Customer reviews initialized");
    }

    // Seed/Sync Products
    const productsToSeed = [
      // ================= MEN'S PRODUCTS =================
      {
        name: "Kashmiri Wool Embroidered Shawl — Signature Black",
        slug: "kashmiri-wool-embroidered-shawl-black",
        category: "men",
        subcategory: "Men Shawls",
        price: 6850,
        salePrice: 5750,
        description: "Handcrafted Kashmiri pure woolen shawl with intricate zari and resham embroidery along the borders. Soft, ultra-warm, and supremely regal for festive winter wear.",
        details: "Fabric: 100% Pure Himalayan Combed Wool\nLength: 2.75 Meters (Full Men's Shawl)\nWidth: 54 Inches\nEmbroidery: Authentic Kashmiri Tilla & Needlework\nFinish: Featherlight, Natural Warmth Drape\nPackaging: Luxury Daud Fabrics Hard Gift Box",
        stock: 35,
        images: JSON.stringify(["/images/men/shawl1.jpg", "/images/men/shawl2.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: true,
      },
      {
        name: "Heritage Pashmina Wool Shawl — Walnut Brown",
        slug: "heritage-pashmina-wool-shawl-walnut",
        category: "men",
        subcategory: "Men Shawls",
        price: 7450,
        salePrice: 6200,
        description: "Exquisite Pashmina blend shawl in deep earthy walnut tone. Tailored for gentlemanly winter gatherings, Jummah prayers, and formal weddings.",
        details: "Fabric: High-Count Pashmina & Lambswool Blend\nDimensions: 2.75m x 54 inches\nWeave: Classic Diamond Twill\nTouch: Cashmere-Soft\nIncludes: Signature Daud Fabrics Gold Seal Box",
        stock: 28,
        images: JSON.stringify(["/images/men/shawl2.jpg", "/images/men/shawl3.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: true,
      },
      {
        name: "Royal Egyptian Cotton Latha — Crisp Fall 4.5m",
        slug: "royal-egyptian-cotton-latha-unstitched",
        category: "men",
        subcategory: "Unstitched Cotton",
        price: 4450,
        salePrice: 3850,
        description: "Premium high thread-count combed Egyptian Giza cotton with crisp fall, natural luster, and ultra-breathable weave for formal and daily wear.",
        details: "Fabric: 100% Long Staple Combed Egyptian Cotton\nCutting: 4.5 Meters Standard Suit\nWidth: 54 Inches (Bara Arz)\nFinish: Royal Crisp Fall / Soft Touch\nIncludes: Signature Daud Fabrics Gold Embossed Buttons",
        stock: 45,
        images: JSON.stringify(["/images/men/shawl3.jpg", "/images/men/shawl4.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: true,
      },
      {
        name: "Classic Superfine Boski Silk Suit — 7.5m Fall Finish",
        slug: "classic-superfine-boski-silk-suit",
        category: "men",
        subcategory: "Pure Boski",
        price: 6950,
        salePrice: 5850,
        description: "Timeless traditional Boski spun silk suit with signature liquid drape, graceful sheen, and unparalleled comfort for festive occasions and Eid.",
        details: "Fabric: Premium Spun Boski Silk (Heavy Weight 10 Paund)\nCutting: 7.5 Meters Boski Length\nWidth: 36 Inches\nFeel: Silky Soft Drape with Subtle Shimmer\nPackaging: Luxury Daud Fabrics Hard Gift Box",
        stock: 30,
        images: JSON.stringify(["/images/men/shawl4.jpg", "/images/men/shawl1.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: true,
      },
      {
        name: "Executive Karandi Textured Fabric Suit — Charcoal",
        slug: "executive-karandi-textured-suit-charcoal",
        category: "men",
        subcategory: "Karandi",
        price: 5200,
        salePrice: 4450,
        description: "Traditional hand-feel Karandi weave with organic slub texture, rich depth of tone, and sturdy yet breathable structure for all-season styling.",
        details: "Fabric: 100% Pure Combed Karandi Yarn\nCutting: 4.5 Meters Unstitched Suit\nWidth: 54 Inches\nTexture: Textured Slub Handloom Feel\nSeason: Autumn / Winter / Spring",
        stock: 32,
        images: JSON.stringify(["/images/men/shawl5.jpg", "/images/men/shawl6.jpg"]),
        isActive: true,
        isFeatured: false,
        isBestseller: true,
      },
      {
        name: "Luxury Velvet Embroidered Festive Shawl — Midnight Navy",
        slug: "luxury-velvet-embroidered-festive-shawl",
        category: "men",
        subcategory: "Men Shawls",
        price: 8500,
        salePrice: 7200,
        description: "Ultra-luxurious micro-velvet shawl with subtle antique gold embroidery on pallu and borders. The ultimate statement piece for winter weddings.",
        details: "Fabric: Micro-Velvet 9000 with Silk Lining\nLength: 2.75 Meters\nEmbroidery: Antique Zari & Tilla Work\nWeight: Premium Heavy Fall",
        stock: 20,
        images: JSON.stringify(["/images/men/shawl6.jpg", "/images/men/shawl7.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: false,
      },
      {
        name: "Pure Handwoven Woolen Winter Shawl — Camel Beige",
        slug: "pure-handwoven-woolen-winter-shawl-camel",
        category: "men",
        subcategory: "Men Shawls",
        price: 5950,
        salePrice: 4950,
        description: "Authentic Swati handloom woven wool shawl in sophisticated camel beige with ethnic woven geometric border trims.",
        details: "Fabric: 100% Handspun Pure Wool\nCutting: Standard 2.75m Men's Shawl\nOrigin: Swat Valley Artisans\nCare: Dry Clean Only",
        stock: 25,
        images: JSON.stringify(["/images/men/shawl7.jpg", "/images/men/shawl8.jpg"]),
        isActive: true,
        isFeatured: false,
        isBestseller: false,
      },
      {
        name: "Regal Zari Border Embroidered Shawl — Maroon Velvet",
        slug: "regal-zari-border-shawl-maroon",
        category: "men",
        subcategory: "Men Shawls",
        price: 7950,
        salePrice: 6650,
        description: "Deep royal maroon shawl highlighted with gold resham border craftsmanship and silk tassel finishing.",
        details: "Fabric: Fine Lambswool with Zari Borders\nLength: 2.75 Meters\nWidth: 54 Inches\nPackaging: Luxury Daud Fabrics Brand Box",
        stock: 22,
        images: JSON.stringify(["/images/men/shawl8.jpg", "/images/men/shawl1.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: true,
      },

      // ================= WOMEN'S PRODUCTS =================
      {
        name: "Luxury Embroidered Swiss Lawn 3-Piece — Rose Bloom",
        slug: "luxury-embroidered-swiss-lawn-rose-bloom",
        category: "women",
        subcategory: "3-Piece Lawn",
        price: 5950,
        salePrice: 4850,
        description: "Exquisite Pakistani designer unstitched 3-piece suit featuring high-density digital lawn shirt, heavily embroidered organza neckline, pure chiffon dupatta, and dyed cambric trouser.",
        details: "Shirt: 3.0 Meters Digital Printed Swiss Lawn with Embroidered Neck Patch\nDupatta: 2.5 Meters Pure Bamburg Chiffon with Four-Sided Borders\nTrouser: 2.5 Meters Dyed Cambric Cotton\nSeason: Spring / Summer Festive",
        stock: 40,
        images: JSON.stringify(["/images/women/new1.jpg", "/images/women/new1.1.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: true,
      },
      {
        name: "Pure Silk Jacquard Festive 3-Piece — Champagne Gold",
        slug: "pure-silk-jacquard-champagne-gold",
        category: "women",
        subcategory: "Silk Jacquard",
        price: 7650,
        salePrice: 6350,
        description: "Opulent pure silk jacquard weave with shimmering gold and copper zari work. Paired with a delicate organza jacquard dupatta and matching silk trouser.",
        details: "Shirt: 3.15 Meters Pure Jacquard Silk with Gold Zari Motif\nDupatta: 2.5 Meters Woven Jacquard Organza with Tassels\nTrouser: 2.5 Meters Dyed Pure Raw Silk\nOccasion: Weddings, Festive Dinners, Formal Gatherings",
        stock: 30,
        images: JSON.stringify(["/images/women/new2.jpg", "/images/women/new2.2.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: true,
      },
      {
        name: "Handcrafted Chikan Kari Pure Cotton 2-Piece — Pure Ivory",
        slug: "handcrafted-chikan-kari-pure-ivory",
        category: "women",
        subcategory: "Chikan Kari",
        price: 4800,
        salePrice: 3950,
        description: "Authentic Chikan Kari thread embroidery on breathable pure lawn voile with scalloped daman and sleeves. Classic Eastern elegance.",
        details: "Shirt: 3.0 Meters Heavy Embroidered Chikan Kari Voile\nTrouser: 2.5 Meters Pure Cotton Cambric with Embroidered Daman Patch\nSeason: Summer Everyday & Casual Gatherings",
        stock: 35,
        images: JSON.stringify(["/images/women/new3.jpg", "/images/women/new3.1.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: true,
      },
      {
        name: "Royal Chiffon Embroidered Wedding 3-Piece — Mint Emerald",
        slug: "royal-chiffon-embroidered-mint-emerald",
        category: "women",
        subcategory: "Chiffon Formal",
        price: 8900,
        salePrice: 7500,
        description: "Breathtaking mint emerald chiffon adorned with hand-embellished sequins, tilla work, and pearls. Includes raw silk inner slip and embroidered dupatta.",
        details: "Shirt: 3.25 Meters Embroidered Chiffon with Hand-Work Sequins & Pearls\nInner Slip: 2.5 Meters Dyed Grip Silk\nDupatta: 2.5 Meters Embroidered Chiffon with Cutwork Borders\nTrouser: 2.5 Meters Pure Raw Silk",
        stock: 22,
        images: JSON.stringify(["/images/women/new4.jpg", "/images/women/new4.4.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: false,
      },
      {
        name: "Digital Printed Swiss Voile 3-Piece — Kashmir Flora",
        slug: "digital-printed-swiss-voile-kashmir-flora",
        category: "women",
        subcategory: "Swiss Voile",
        price: 4250,
        salePrice: 3450,
        description: "Featherlight Swiss voile fabric featuring modern abstract Kashmiri florals, matched with a soft voile dupatta and dyed trousers.",
        details: "Shirt: 3.0 Meters Premium Swiss Voile\nDupatta: 2.5 Meters Soft Swiss Voile\nTrouser: 2.5 Meters Cambric Cotton\nFeel: Ultra-soft, cool against summer heat",
        stock: 45,
        images: JSON.stringify(["/images/women/new5.jpg", "/images/women/new5.1.jpg"]),
        isActive: true,
        isFeatured: false,
        isBestseller: true,
      },
      {
        name: "Festive Organza Zari Embellished Suit — Golden Amber",
        slug: "festive-organza-zari-golden-amber",
        category: "women",
        subcategory: "Organza Festive",
        price: 8200,
        salePrice: 6900,
        description: "Golden amber sheer organza shirt with heavy zari threadwork, paired with silk pants and a lavish four-sided border dupatta.",
        details: "Shirt: 3.0 Meters Pure Organza with Resham Zari\nDupatta: 2.5 Meters Organza Zari Jaal\nTrouser: 2.5 Meters Silk Trouser",
        stock: 25,
        images: JSON.stringify(["/images/women/new6.jpg", "/images/women/new6.1.webp"]),
        isActive: true,
        isFeatured: true,
        isBestseller: false,
      },
      {
        name: "Classic Velvet Embroidered Shawl & Suit — Ruby Crimson",
        slug: "classic-velvet-embroidered-ruby-crimson",
        category: "women",
        subcategory: "Velvet Festive",
        price: 9800,
        salePrice: 8400,
        description: "Heavy micro-velvet unstitched suit with gold tilla embroidery and a signature matching velvet embroidered shawl.",
        details: "Shirt & Trouser: 5.0 Meters Luxury Micro Velvet\nShawl: 2.75 Meters Embroidered Velvet Shawl\nSeason: Winter Weddings",
        stock: 18,
        images: JSON.stringify(["/images/women/new7.jpg", "/images/women/new7.1.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: true,
      },
      {
        name: "Luxury Summer Jacquard 3-Piece Ensemble — Cobalt Azure",
        slug: "luxury-summer-jacquard-cobalt-azure",
        category: "women",
        subcategory: "Jacquard",
        price: 6400,
        salePrice: 5350,
        description: "Vibrant cobalt blue with woven gold threads, paired with a lightweight jacquard dupatta and matching dyed trousers.",
        details: "Shirt: 3.0m Jacquard Lawn\nDupatta: 2.5m Jacquard Voile\nTrouser: 2.5m Dyed Cotton",
        stock: 30,
        images: JSON.stringify(["/images/women/new8.jpg", "/images/women/new8.1.jpg"]),
        isActive: true,
        isFeatured: false,
        isBestseller: true,
      },
      {
        name: "Pastel Embroidered Cotton Net Suit — Powder Blue",
        slug: "pastel-embroidered-cotton-net-powder-blue",
        category: "women",
        subcategory: "Cotton Net",
        price: 6900,
        salePrice: 5800,
        description: "Subtle and sophisticated powder blue cotton net shirt with intricate floral threadwork and scalloped lace details.",
        details: "Shirt: 3.0m Cotton Net\nSlip: 2.5m Cotton Silk\nDupatta: 2.5m Organza Net",
        stock: 28,
        images: JSON.stringify(["/images/women/new9.webp", "/images/women/new9.1.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: false,
      },
      {
        name: "Royal Crimson Festive Lawn 3-Piece — Scarlet Bloom",
        slug: "royal-crimson-festive-lawn-scarlet-bloom",
        category: "women",
        subcategory: "3-Piece Lawn",
        price: 5750,
        salePrice: 4750,
        description: "Rich scarlet red lawn with heavy neckline embroidery and printed chiffon dupatta for festive evenings.",
        details: "Shirt: 3.0m Luxury Lawn\nDupatta: 2.5m Chiffon\nTrouser: 2.5m Cambric",
        stock: 35,
        images: JSON.stringify(["/images/women/new10.jpg", "/images/women/new10.1.jpg"]),
        isActive: true,
        isFeatured: false,
        isBestseller: true,
      },
      {
        name: "Emerald Gold Brocade Silk Suit — Regal Malachite",
        slug: "emerald-gold-brocade-regal-malachite",
        category: "women",
        subcategory: "Silk Formal",
        price: 8200,
        salePrice: 6950,
        description: "Shimmering emerald green silk with woven gold brocade motifs and a matching festive organza dupatta.",
        details: "Shirt: 3.15m Brocade Silk\nDupatta: 2.5m Jacquard Organza\nTrouser: 2.5m Raw Silk",
        stock: 20,
        images: JSON.stringify(["/images/women/new11.jpg", "/images/women/new11.1.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: false,
      },
      {
        name: "Sapphire Blue Embroidered Lawn 3-Piece — Royal Lapis",
        slug: "sapphire-blue-embroidered-lawn-royal-lapis",
        category: "women",
        subcategory: "3-Piece Lawn",
        price: 5850,
        salePrice: 4900,
        description: "Deep sapphire blue lawn with crisp white and gold floral threadwork, paired with a printed silk dupatta.",
        details: "Shirt: 3.0m Lawn\nDupatta: 2.5m Medium Silk\nTrouser: 2.5m Cotton",
        stock: 32,
        images: JSON.stringify(["/images/women/new12.jpg", "/images/women/new12.1.jpg"]),
        isActive: true,
        isFeatured: false,
        isBestseller: true,
      },
      {
        name: "Amber Ochre Chiffon 3-Piece — Sunburst Gold",
        slug: "amber-ochre-chiffon-sunburst-gold",
        category: "women",
        subcategory: "Chiffon Formal",
        price: 7800,
        salePrice: 6500,
        description: "Warm amber tone chiffon with delicate gold mirror embroidery and a flowing chiffon dupatta.",
        details: "Shirt: 3.25m Embroidered Chiffon\nDupatta: 2.5m Chiffon with Borders\nTrouser: 2.5m Silk",
        stock: 24,
        images: JSON.stringify(["/images/women/new13.jpg", "/images/women/new13.1.jpg"]),
        isActive: true,
        isFeatured: false,
        isBestseller: false,
      },
      {
        name: "Pearl Blush Raw Silk Formal — Dusty Petal",
        slug: "pearl-blush-raw-silk-dusty-petal",
        category: "women",
        subcategory: "Raw Silk",
        price: 8400,
        salePrice: 7100,
        description: "Elegant dusty pink raw silk formal unstitched suit with delicate silver tilla and pearl work.",
        details: "Shirt: 3.0m Pure Raw Silk 80g\nDupatta: 2.5m Silk Net\nTrouser: 2.5m Raw Silk",
        stock: 22,
        images: JSON.stringify(["/images/women/new14.jpg", "/images/women/new14.1.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: false,
      },
      {
        name: "Midnight Onyx Festive Velvet Suit — Jet Black",
        slug: "midnight-onyx-festive-velvet-jet-black",
        category: "women",
        subcategory: "Velvet Festive",
        price: 9400,
        salePrice: 7950,
        description: "Classic jet black velvet with opulent gold antique zari hand embellishments on gala and daman.",
        details: "Shirt: 3.0m Micro Velvet 9000\nDupatta: 2.5m Embroidered Organza\nTrouser: 2.5m Raw Silk",
        stock: 19,
        images: JSON.stringify(["/images/women/new15.jpg", "/images/women/new15.5.webp"]),
        isActive: true,
        isFeatured: true,
        isBestseller: true,
      },
      {
        name: "Lilac Whisper Embroidered Lawn — Soft Lavender",
        slug: "lilac-whisper-embroidered-lawn-soft-lavender",
        category: "women",
        subcategory: "3-Piece Lawn",
        price: 5600,
        salePrice: 4650,
        description: "Pastel lilac luxury lawn with intricate white schiffli embroidery and digital silk dupatta.",
        details: "Shirt: 3.0m Schiffli Lawn\nDupatta: 2.5m Digital Silk\nTrouser: 2.5m Dyed Cotton",
        stock: 38,
        images: JSON.stringify(["/images/women/new16.jpg", "/images/women/new16.1.jpg"]),
        isActive: true,
        isFeatured: false,
        isBestseller: true,
      },
      {
        name: "Ruby Red Zari Festive Formal Suit — Garnet Glamour",
        slug: "ruby-red-zari-festive-garnet-glamour",
        category: "women",
        subcategory: "Chiffon Formal",
        price: 8600,
        salePrice: 7300,
        description: "Deep garnet red chiffon with shimmering golden thread and sequins embroidery.",
        details: "Shirt: 3.25m Chiffon\nDupatta: 2.5m Chiffon\nTrouser: 2.5m Raw Silk",
        stock: 21,
        images: JSON.stringify(["/images/women/new17.jpg", "/images/women/new17.1.jpg"]),
        isActive: true,
        isFeatured: false,
        isBestseller: false,
      },
      {
        name: "Ivory Gold Threadwork Suit — Sovereign Cream",
        slug: "ivory-gold-threadwork-sovereign-cream",
        category: "women",
        subcategory: "Chikan Kari",
        price: 6750,
        salePrice: 5600,
        description: "Prestigious ivory cotton lawn with dense gold zari embroidery on front and sleeve panels.",
        details: "Shirt: 3.0m Heavy Embroidered Cotton\nDupatta: 2.5m Woven Jacquard\nTrouser: 2.5m Cambric",
        stock: 30,
        images: JSON.stringify(["/images/women/new18.jpg", "/images/women/new18.1.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: true,
      },
      {
        name: "Dusty Rose Jacquard Ensemble — Vintage Blush",
        slug: "dusty-rose-jacquard-vintage-blush",
        category: "women",
        subcategory: "Silk Jacquard",
        price: 7200,
        salePrice: 6100,
        description: "Subtle vintage rose jacquard shirt with golden borders and a featherlight organza dupatta.",
        details: "Shirt: 3.15m Jacquard Lawn\nDupatta: 2.5m Organza\nTrouser: 2.5m Raw Silk",
        stock: 26,
        images: JSON.stringify(["/images/women/new19.jpg", "/images/women/new19.1.jpg"]),
        isActive: true,
        isFeatured: false,
        isBestseller: false,
      },
      {
        name: "Champagne Gold Zari 3-Piece Suit — Imperial Glow",
        slug: "champagne-gold-zari-imperial-glow",
        category: "women",
        subcategory: "Organza Festive",
        price: 8900,
        salePrice: 7600,
        description: "Mesmerizing champagne gold festive unstitched formal suit with comprehensive zari and cutwork details.",
        details: "Shirt: 3.25m Organza with Zari Jaal\nDupatta: 2.5m Organza Cutwork\nTrouser: 2.5m Raw Silk",
        stock: 24,
        images: JSON.stringify(["/images/women/new20.jpg", "/images/women/new20.1.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: true,
      },
      {
        name: "Signature Floral Printed Lawn 3-Piece — Meadow Breeze",
        slug: "signature-floral-printed-lawn-meadow-breeze",
        category: "women",
        subcategory: "3-Piece Lawn",
        price: 4950,
        salePrice: 3950,
        description: "Refreshing botanical prints on high-density combed lawn with a soft voile dupatta.",
        details: "Shirt: 3.0m Printed Lawn\nDupatta: 2.5m Voile Dupatta\nTrouser: 2.5m Dyed Cotton",
        stock: 45,
        images: JSON.stringify(["/images/women/image1.jpg", "/images/women/image2.jpg"]),
        isActive: true,
        isFeatured: false,
        isBestseller: true,
      },
      {
        name: "Festive Gold Foil Cotton Silk Suit — Radiance",
        slug: "festive-gold-foil-cotton-silk-radiance",
        category: "women",
        subcategory: "Silk Formal",
        price: 6600,
        salePrice: 5450,
        description: "Lustrous cotton silk blend with metallic gold block foil patterns and dyed silk pants.",
        details: "Shirt: 3.0m Cotton Silk\nDupatta: 2.5m Jacquard Organza\nTrouser: 2.5m Cotton Silk",
        stock: 28,
        images: JSON.stringify(["/images/women/image3.jpg", "/images/women/image4.jpg"]),
        isActive: true,
        isFeatured: false,
        isBestseller: false,
      },
      {
        name: "Traditional Sindhi Ajrak Print Lawn — Heritage Red",
        slug: "traditional-sindhi-ajrak-heritage-red",
        category: "women",
        subcategory: "3-Piece Lawn",
        price: 4600,
        salePrice: 3750,
        description: "Timeless traditional Sindhi Ajrak geometric patterns on pure unstitched lawn.",
        details: "Shirt: 3.0m Ajrak Lawn\nDupatta: 2.5m Lawn Dupatta\nTrouser: 2.5m Dyed Cotton",
        stock: 35,
        images: JSON.stringify(["/images/women/image5.jpg", "/images/women/image6.jpg"]),
        isActive: true,
        isFeatured: false,
        isBestseller: false,
      },
      {
        name: "Modern Kashmiri Paisley 3-Piece — Twilight Indigo",
        slug: "modern-kashmiri-paisley-twilight-indigo",
        category: "women",
        subcategory: "3-Piece Lawn",
        price: 5200,
        salePrice: 4200,
        description: "Deep indigo blue with Kashmiri paisley motifs, embroidered neckline patch, and chiffon dupatta.",
        details: "Shirt: 3.0m Lawn with Embroidered Patch\nDupatta: 2.5m Chiffon\nTrouser: 2.5m Dyed Cotton",
        stock: 30,
        images: JSON.stringify(["/images/women/image7.jpg", "/images/women/image8.jpg"]),
        isActive: true,
        isFeatured: false,
        isBestseller: true,
      },

      // ================= KIDS' PRODUCTS =================
      {
        name: "Boys Classic Pure Cotton Kurta Fabric (Ages 4-12)",
        slug: "boys-classic-pure-cotton-kurta-fabric",
        category: "kids",
        subcategory: "Boys Kurta",
        price: 1950,
        salePrice: 1550,
        description: "Hypoallergenic, ultra-soft 100% combed Pakistani cotton fabric specially woven for kids. Gentle on skin with vibrant festive tones.",
        details: "Fabric: 100% Combed Baby Cotton\nCutting: 2.25 Meters (Sufficient for Kurta Shalwar up to Age 12)\nWidth: 40 Inches\nFeatures: Breathable, anti-chafing, color-fast guarantee",
        stock: 35,
        images: JSON.stringify(["/images/men/shawl4.jpg", "/images/men/shawl3.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: true,
      },
      {
        name: "Festive Embroidered Boys Kurta Set Fabric — Royal Gold",
        slug: "festive-embroidered-boys-kurta-fabric",
        category: "kids",
        subcategory: "Boys Festive",
        price: 2450,
        salePrice: 1990,
        description: "Includes delicate machine resham embroidery on collar and cuff patches with premium wash-and-wear base fabric.",
        details: "Fabric: Wash & Wear with embroidered neckline motif\nCutting: 2.5 Meters\nWidth: 40 Inches\nIdeal for: Eid, Weddings & School Traditional Day events",
        stock: 25,
        images: JSON.stringify(["/images/men/shawl1.jpg", "/images/men/shawl2.jpg"]),
        isActive: true,
        isFeatured: true,
        isBestseller: false,
      },
      {
        name: "Girls Printed Lawn Festive 2-Piece Fabric Set",
        slug: "girls-printed-lawn-festive-2-piece",
        category: "kids",
        subcategory: "Girls Lawn",
        price: 2200,
        salePrice: 1750,
        description: "Colorful pastel floral printed Pakistani lawn fabric with matching chiffon dupatta for young girls (Ages 5-13).",
        details: "Shirt: 2.25 Meters Digital Printed Soft Lawn\nDupatta: 2.0 Meters Soft Feather Chiffon\nComfort: Non-irritating, easy to wash, bright lasting colors",
        stock: 30,
        images: JSON.stringify(["/images/women/image10.jpg", "/images/women/image11.jpg"]),
        isActive: true,
        isFeatured: false,
        isBestseller: true,
      },
    ];

    for (const item of productsToSeed) {
      await db
        .insert(products)
        .values(item)
        .onConflictDoUpdate({
          target: products.slug,
          set: {
            name: item.name,
            category: item.category,
            subcategory: item.subcategory,
            price: item.price,
            salePrice: item.salePrice,
            description: item.description,
            details: item.details,
            images: item.images,
            isActive: item.isActive,
            isFeatured: item.isFeatured,
            isBestseller: item.isBestseller,
          },
        });
    }
    console.log(`Seed: Synced and seeded ${productsToSeed.length} luxury fabric products`);

    console.log("Seed: Database seeding completed successfully!");
  } catch (error) {
    console.error("Seed error:", error);
  }
}
